route_index:
    path: /
    controller: App\Controller\StaticController::homepage

route_qualify1:
    path: /qualification-1/
    controller: App\Controller\QualificationController::qualification1

route_qualify2:
    path: /qualification-2/
    controller: App\Controller\QualificationController::qualification2

route_qualify3:
    path: /qualification-3/
    controller: App\Controller\QualificationController::qualification3

route_resultats:
    path: /resultats/
    controller: App\Controller\QualificationController::resultats

route_gotods:
    path: /redirection-ds/
    controller: App\Controller\QualificationController::gotods

route_pas_de_demarche:
    path: /pas-de-resultats/
    controller: App\Controller\QualificationController::pasdedemarche

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation
