# Static
route_index:
    path: /
    controller: App\Controller\StaticController::homepage

route_static_comment_ca_marche:
    path: /comment-ca-marche
    controller: App\Controller\StaticController::comment

route_static_cgu:
    path: /cgu
    controller: App\Controller\StaticController::cgu

route_static_faq:
    path: /faq
    controller: App\Controller\StaticController::faq

route_static_contact:
    path: /contact
    controller: App\Controller\StaticController::contact

route_static_infosTravaux:
    path: /travaux/{typeTravaux}
    controller: App\Controller\StaticController::infosTravaux

# Qualification
route_qualify1:
    path: /qualification/etape-1/
    controller: App\Controller\QualificationController::qualification1

route_qualify2:
    path: /qualification/etape-2/
    controller: App\Controller\QualificationController::qualification2

route_resultats:
    path: /qualification/resultats/
    controller: App\Controller\QualificationController::resultats

route_gotods:
    path: /qualification/redirection-ds/
    controller: App\Controller\QualificationController::gotods

route_pas_de_demarche:
    path: /qualification/pas-de-resultats/
    controller: App\Controller\QualificationController::pasdedemarche

# Backoffice
route_backoffice_ville_tableauDeBord:
    path: /backoffice/ville/
    controller: App\Controller\BackofficeVilleController::tableauDeBord

route_backoffice_ville_telechargerDemande:
    path: /backoffice/ville/telecharger-demande
    controller: App\Controller\BackofficeVilleController::telechargerDemande

# External bundles
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation
