route_index:
    path: /
    controller: App\Controller\StaticController::homepage

route_demandeur_dashboard:
    path: /demandeur-dashboard
    controller: App\Controller\DemandeurController::dashboard

route_demandeur_voir_demande:
    path: /demandeur-voir-demande
    controller: App\Controller\DemandeurController::voirDemande

route_dashboard_instructeur:
    path: /dashboard-instructeur
    controller: App\Controller\InstructeurController::dashboard

route_dashboard_mairie:
    path: /dashboard-mairie
    controller: App\Controller\MairieController::dashboard

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"