version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-browsers

    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build service
        command: make build
    - run:
        name: Install dependencies
        command: make install
    - run:
        name: Run unit tests
        command: docker exec -it $(docker ps -qf "name=project_php") bin/phpunit