version: 2
jobs:
  build:
    docker:
    # using custom image, see .circleci/images/primary/Dockerfile
    - image: circleci/cci-demo-docker-primary:0.0.2

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build service
        command: make build
    - run: make tests