version: 2
jobs:
  build:
    machine: true

    steps:
    - checkout
    - run:
        name: Build services
        command: make build
    - run:
        name: Install dependencies
        command: make composer-install
    - run:
        name: Run unit tests
        command: make tests
    - run:
        name: Check code style
        command: make cs-check
