version: 2
jobs:
  build:
    docker:
    # using custom image, see .circleci/images/primary/Dockerfile
    - image: circleci/cci-demo-docker-primary:0.0.2
    - image: postgres:9.4.1
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: contacts
    working_directory: /go/src/github.com/circleci/cci-demo-docker

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build service
        command: make build
    - run: make tests