version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-browsers

    steps:
    - checkout
    - run:
        name: Build service
        command: make build
    - run:
        name: Run unit tests
        command: make tests